### ISSUE TITLE
Scraper code

### ISSUE THREAD

**Issue by DarkGL** [ModestSerhat/buff163-ids#2]
Could you share code of the scrapper you use to get ids ?

**Comment by DoseOfCode** [comment]
https://buff.163.com/market/buy_order/to_create?game=csgo

Scrape the HTTP endpoint this page uses with cookies of a logged in user

**Comment by ModestSerhat** [comment]
You can also scrape the page https://buff.163.com/goods/{goods_id}#tab=selling without an user login but you would need a goods_id parameter (or a range of numbers of goods_id parameters) to get an HTML response, the name of the item is the first h1 element in the page. The

The name of the item is Chinese without any cookies, you can get the English name by setting the Locale-Supported cookie to 'en' and requesting the page.

**Comment by M3chaKret** [comment]
> https://buff.163.com/market/buy_order/to_create?game=csgo
> 
> Scrape the HTTP endpoint this page uses with cookies of a logged in user

Hi, could you explain how to add cookies of a logged in user,
I'm trying to solve some of my problem but I get "Login Required"
