### ISSUE TITLE
Adding other games

### ISSUE THREAD

**Issue by DarkGL** [ModestSerhat/buff163-ids#3]
Would it be also possible to add ids from other games ? ( dota2 )

Probably in separate file.

**Comment by ModestSerhat** [comment]
Although, I don't keep track of other games' items such as Dota 2 and Team Fortress 2 feel free use this spreadsheet to make a repository for other games similar to mine. The spreadsheet was from someone on Twitter who scraped every Buff Goods ID with the item name, game and item type.

https://docs.google.com/spreadsheets/d/1H13FGLTk6ddbuf3Gon4thHr7YfFY6iq42msGuxKghNc/edit?usp=sharing
